### ISSUE TITLE
Logout from Artemis

### ISSUE THREAD

**Issue by dfuchss** [kit-sdq/intelligrade#64]
You should be able to log out from Artemis, but I think in the last version the Cookie for Shibboleth was still present … so I directly logged in again :)

**Comment by Feuermagier** [comment]
https://github.com/kit-sdq/intelligrade/blob/de38e97ae095797964a4cf9231f455fbf4a5ec14/src/main/java/edu/kit/kastel/sdq/intelligrade/login/CefUtils.java#L52 this code deletes the cookie, I just didn't have the time yet to integrate it properly. Note that it's important that exactly this code is used, it is placed at exactly the same place in the JCEF initialization sequence, and that it is called from the right thread. Otherwise, random JCEF freezes will happen

**Comment by CDaut** [comment]
Working on that in https://github.com/kit-sdq/intelligrade/tree/logout_button
